singleQuote: true
quoteProps: consistent
plugins:
  - "@trivago/prettier-plugin-sort-imports"
  - prettier-plugin-packagejson
  - prettier-plugin-tailwindcss
importOrder:
  - ^node:.*
  - <THIRD_PARTY_MODULES>
  - "^@repo"
  - "^@/"
  - "^[./]"
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderSideEffects: false
tailwindFunctions:
  - cva
  - cx
